INSERT INTO movie (Titulo, Director, Anio, Duracion, Genero) VALUES ('Avatar', 'James Cameron', '2009', '162', 'Acción');
INSERT INTO movie (Titulo, Director, Anio, Duracion, Genero) VALUES ('Avengers: Endgame', 'Anthony y Joe Russo', '2019', '181', 'Acción');
INSERT INTO movie (Titulo, Director, Anio, Duracion, Genero) VALUES ('Titanic', 'James Cameron', '1997', '195', 'Romance');
INSERT INTO movie (Titulo, Director, Anio, Duracion, Genero) VALUES ('Batman: el caballero de la noche', 'Christopher Nolan', '2008', '152', 'Acción');
INSERT INTO movie (Titulo, Director, Anio, Duracion, Genero) VALUES ('El origen', 'Christopher Nolan', '2010', '148', 'Ciencia ficción');
INSERT INTO movie (Titulo, Director, Anio, Duracion, Genero) VALUES ('Sueño de fuga', 'Frank Darabont', '1994', '142', 'Drama');
INSERT INTO movie (Titulo, Director, Anio, Duracion, Genero) VALUES ('Forrest Gump', 'Robert Zemeckis', '1994', '142', 'Drama');
INSERT INTO movie (Titulo, Director, Anio, Duracion, Genero) VALUES ('Jurassic Park', 'Steven Spielberg', '1993', '127', 'Aventura');
INSERT INTO movie (Titulo, Director, Anio, Duracion, Genero) VALUES ('Matrix', 'Lana y Lilly Wachowski', '1999', '136', 'Ciencia ficción');
INSERT INTO movie (Titulo, Director, Anio, Duracion, Genero) VALUES ('El padrino', 'Francis Ford Coppola', '1972', '175', 'Crimen');
INSERT INTO movie (Titulo, Director, Anio, Duracion, Genero) VALUES ('El rey leon', 'Roger Allers y Rob Minkoff', '1994', '88', 'Animación');
INSERT INTO movie (Titulo, Director, Anio, Duracion, Genero) VALUES ('Los vengadores', 'Joss Whedon', '2012', '143', 'Acción');
INSERT INTO movie (Titulo, Director, Anio, Duracion, Genero) VALUES ('Tiempos violentos', 'Quentin Tarantino', '1994', '154', 'Crimen');
INSERT INTO movie (Titulo, Director, Anio, Duracion, Genero) VALUES ('E.T.', 'Steven Spielberg', '1982', '115', 'Ciencia ficción');
INSERT INTO movie (Titulo, Director, Anio, Duracion, Genero) VALUES ('El silencio de los inocentes', 'Jonathan Demme', '1991', '118', 'Suspense');
INSERT INTO movie (Titulo, Director, Anio, Duracion, Genero) VALUES ('El gran hotel Budapest', 'Wes Anderson', '2014', '99', 'Comedia');
INSERT INTO movie (Titulo, Director, Anio, Duracion, Genero) VALUES ('La La Land', 'Damien Chazelle', '2016', '128', 'Musical');
INSERT INTO movie (Titulo, Director, Anio, Duracion, Genero) VALUES ('Interstelar', 'Christopher Nolan', '2014', '169', 'Ciencia ficción');
INSERT INTO movie (Titulo, Director, Anio, Duracion, Genero) VALUES ('Red social', 'David Fincher', '2010', '120', 'Drama');
INSERT INTO movie (Titulo, Director, Anio, Duracion, Genero) VALUES ('Pantera Negra', 'Ryan Coogler', '2018', '134', 'Acción');
INSERT INTO movie (Titulo, Director, Anio, Duracion, Genero) VALUES ('Revenant: el renacido', 'Alejandro González Iñárritu', '2015', '156', 'Aventura');
INSERT INTO movie (Titulo, Director, Anio, Duracion, Genero) VALUES ('Los infiltrados', 'Martin Scorsese', '2006', '151', 'Crimen');
INSERT INTO movie (Titulo, Director, Anio, Duracion, Genero) VALUES ('Mad Max: furia en el camino', 'George Miller', '2015', '120', 'Acción');
INSERT INTO movie (Titulo, Director, Anio, Duracion, Genero) VALUES ('El gran Gatsby', 'Baz Luhrmann', '2013', '143', 'Drama');
INSERT INTO movie (Titulo, Director, Anio, Duracion, Genero) VALUES ('The Shape of Water', 'Guillermo del Toro', '2017', '123', 'Fantasía');
INSERT INTO movie (Titulo, Director, Anio, Duracion, Genero) VALUES ('Whiplash', 'Damien Chazelle', '2014', '107', 'Drama');
INSERT INTO movie (Titulo, Director, Anio, Duracion, Genero) VALUES ('Coco', 'Lee Unkrich', '2017', '105', 'Animación');
INSERT INTO movie (Titulo, Director, Anio, Duracion, Genero) VALUES ('Gravedad', 'Alfonso Cuarón', '2013', '91', 'Ciencia ficción');
INSERT INTO movie (Titulo, Director, Anio, Duracion, Genero) VALUES ('Gladiador', 'Ridley Scott', '2000', '155', 'Acción');
INSERT INTO movie (Titulo, Director, Anio, Duracion, Genero) VALUES ('Los ocho más odiados', 'Quentin Tarantino', '2015', '168', 'Western');